name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0.7"
          - "3.1.7"
          - "3.2.8"
          - "3.3.7"
          - "3.4.2"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby & Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          rubygems: "3.3.11"
      - name: Run the default task
        run: bundle exec rake
